[package]
name = "connpipe"
version = "0.1.0"
edition = "2021"
authors = ["1e1001"]

[features]
default = ["gui"]
gui = ["iced"]

[dependencies.logos]
version = "0.12.0"

[dependencies.thiserror]
version = "1.0.30"

[dependencies.ariadne]
version = "0.1.5"

[dependencies.idna]
version = "0.2.3"

[dependencies.iced]
version = "0.3.0"
optional = true
