[package]
name = "connpipe"
version = "0.1.0"
edition = "2021"
authors = ["1e1001"]

[dependencies.mlua]
version = "0.7.4"
features = ["lua54", "vendored", "async", "macros"]

[dependencies.tokio]
version = "1.18"
features = ["full"]

[dependencies.log]
version = "0.4.17"

[dependencies.env_logger]
version = "0.9.0"

[dependencies.thiserror]
version = "1.0"

[dependencies.futures]
version = "0.3.21"

[dependencies.async-trait]
version = "0.1.53"
