[package]
name = "connpipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.logos]
version = "0.12"

[dependencies.thiserror]
version = "1.0"
